---
# This playbook is designed to purge fs2es-indexer and all package dependancies

- name: confirm whether user really meant to purge fs2es-indexer
  hosts: indexers
  gather_facts: false

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to purge fs2es-indexer?
      default: 'no'
      private: no

  tasks:
  - name: exit playbook, if user did not mean to purge fs2es-indexer
    fail:
      msg: >
        "Exiting purge-indexer playbook, fs2es-indexer was NOT purged.
         To purge fs2es-indexer, either say 'yes' on the prompt or
         or use `-e ireallymeanit=yes` on the command line when
         invoking the playbook"
    when: ireallymeanit != 'yes'

- name: purge fs2es-indexer
  hosts: 
    - indexers
  
  tasks:
  - name: stop fs2es systemd service
    ansible.builtin.systemd:
      name: fs2es-indexer.service
      state: stopped

  - name: purge fs2es config directory
    ansible.builtin.file: 
      path: /etc/fs2es-indexer
      state: absent

  - name: purge fs2es systemd service
    ansible.builtin.file: 
      path: /etc/systemd/system/fs2es-indexer.service
      state: absent

- name: purge elasticsearch
  hosts:
    - indexers

  tasks:    
  - name: stop elasticsearch systemd
    ansible.builtin.systemd:
      name: elasticsearch.service
      state: stopped

  - name: purge elasticsearch package
    dnf:
      name: elasticsearch
      state: absent
      enablerepo: elasticsearch

  - name: remove elasticsearch gpg key
    ansible.builtin.rpm_key:
      state: absent
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: remove elasticsearch repo
    yum_repository:
      name: elasticsearch
      state: absent
