---
- name: include validate tasks
  include: validate/main.yml

- name: include configure repo tasks
  include: configure-repo/configure-repo.yml

- name: include install tasks
  include: install-elasticsearch/elasticsearch-install.yml

- name: include configure elasticsearch tasks
  include: configure-elasticsearch/main.yml