- name: enable systemd service
  ansible.builtin.systemd:
    name: elasticsearch.service
    enabled: yes
    daemon_reload: yes


- name: start elasticsearch systemd service
  ansible.builtin.systemd:
    name: elasticsearch.service
    state: started