- name: run setup script
  ansible.builtin.shell: python3 setup.py install
  args:
    chdir: /etc/fs2es-indexer/

- name: gather facts for shares
  shell: /usr/bin/net conf showshare {% for share in samba_shares %}{{ share }}{% endfor %} | grep path | awk '{print $3}'
  register: share_names.stdout

- name: write config file
  template:
    src: config.yml.j2
    dest: /etc/fs2es-indexer/config.yml
    owner: root
  notify: service handler

- name: enable and start systemd service
  ansible.builtin.systemd:
    name: fs2es-indexer.service
    enabled: yes
    state: started