- name: run fs2es-indexer setup script
  ansible.builtin.script: /etc/fs2es-indexer/setup.py install
  args:
    executable: python3

- name: write fs2es-indexer config file
  template:
    src: config.yml.j2
    dest: /etc/fs2es-indexer/config.yml
    owner: "root"
  notify: service handler

- name: enable fs2es-indexer systemd service
  ansible.builtin.systemd:
    name: fsindexer.service
    enabled: yes
    state: started

- name: start fs2es-indexer systemd service
  ansible.builtin.systemd:
    name: fsindexer.service
    state: started